### ISSUE TITLE
IPv6 bug on Windows 10

### ISSUE THREAD

**Issue by tyrelkostyk** [UofSSpaceTeam/robocluster#35]
```Traceback (most recent call last):
  File "USBmanager.py", line 9, in <module>
    ports[port.device] = SerialDriver(port.device,'rover')
  File "c:\users\tyrel\robocluster\robocluster\serialdriver.py", line 137, in __init__
    super().__init__(name, group, loop=loop)
  File "c:\users\tyrel\robocluster\robocluster\device.py", line 52, in __init__
    self._router = Router(self.name, group, loop=self._loop)
  File "c:\users\tyrel\robocluster\robocluster\router.py", line 279, in __init__
    self._caster = Multicaster(group, port, loop=loop)
  File "c:\users\tyrel\robocluster\robocluster\router.py", line 114, in __init__
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_JOIN_GROUP, mreq)
AttributeError: module 'socket' has no attribute 'IPPROTO_IPV6```

**Comment by ottopasuuna** [comment]
We switched to IPv4 so this is no longer an issue.
