### ISSUE TITLE
Weird error when restarting a process

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/robocluster#54]
I'm not sure what exactly causes this, but I think it happens when the robocluster-manager tries to restart a stopped process, and the other processes get confused becuase it creates a new Device with the same name.
```
Traceback (most recent call last):
  File "/home/pi/robocluster/robocluster/looper.py", line 86, in _daemon_wrapper
    await coro(*args, **kwargs)
  File "/home/pi/robocluster/robocluster/device.py", line 208, in _wrapper
    await coro()
  File "./demo/random_stream.py", line 10, in generate
    await device.publish('random', random.random())
  File "/home/pi/robocluster/robocluster/device.py", line 107, in publish
    await self._member.publish(topic, data)
  File "/home/pi/robocluster/robocluster/member.py", line 67, in publish
    await peer.publish(endpoint, data)
  File "/home/pi/robocluster/robocluster/member.py", line 177, in publish
    await self._send(packet)
  File "/home/pi/robocluster/robocluster/member.py", line 213, in _send
    await self._socket.send(size + packet)
  File "/home/pi/robocluster/robocluster/net.py", line 76, in wrapper
    remover(fd)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 352, in remove_writer
    return self._remove_writer(fd)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 316, in _remove_writer
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.5/selectors.py", line 189, in get_key
    return mapping[fileobj]
  File "/usr/lib/python3.5/selectors.py", line 70, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/lib/python3.5/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.5/selectors.py", line 41, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```

**Comment by jpas** [comment]
I think I have an idea of what's going on, but without some code to try and reproduce it I can't be sure.
Can you send me some to so I can?

**Comment by ottopasuuna** [comment]
I believe if you run `examples/manager/demo.py` in one terminal, and run `examples/manager/remote_client.py` in another, the problem occurs sometimes. It does not occur consistantly though, maybe a 1/15 chance.

**Comment by ottopasuuna** [comment]
I also get this error more consistantly than the one above, not sure if they're related:
```
Traceback (most recent call last):                                                        
  File "/home/carl/Programming/usst/robocluster/robocluster/looper.py", line 86, in _daemon_wrapper
    await coro(*args, **kwargs)                                                                         
  File "/home/carl/Programming/usst/robocluster/robocluster/device.py", line 208, in _wrapper
    await coro()                                                                                                                       
  File "Autopilot.py", line 71, in state_machine
    await Autopilot.storage.state()                                                                                                    
  File "Autopilot.py", line 27, in waiting
    await Autopilot.publish('wheelLF', {'SetRPM':0})                                                                                   
  File "/home/carl/Programming/usst/robocluster/robocluster/device.py", line 107, in publish
    await self._member.publish(topic, data)                                                                                            
  File "/home/carl/Programming/usst/robocluster/robocluster/member.py", line 67, in publish        
    await peer.publish(endpoint, data)
  File "/home/carl/Programming/usst/robocluster/robocluster/member.py", line 177, in publish 
    await self._send(packet)
  File "/home/carl/Programming/usst/robocluster/robocluster/member.py", line 213, in _send
    await self._socket.send(size + packet)
  File "/home/carl/miniconda3/envs/robocluster2/lib/python3.5/asyncio/futures.py", line 383, in __iter__
    return self.result()  # May raise too.          
  File "/home/carl/miniconda3/envs/robocluster2/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception                  
  File "/home/carl/Programming/usst/robocluster/robocluster/net.py", line 80, in wrapper   
    result = func(*args, **kwargs)                                
BrokenPipeError: [Errno 32] Broken pipe     
```
