### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv'

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceTeam/robocluster#59]
```
'NoneType' object has no attribute 'recv'
Traceback (most recent call last):
  File "/home/pi/robocluster/robocluster/member.py", line 228, in _recv                                                                
    data = await self._socket.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
Got remote stop DriveControl
'NoneType' object has no attribute 'recv'
Traceback (most recent call last):
  File "/home/pi/robocluster/robocluster/member.py", line 228, in _recv                                                                
    data = await self._socket.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
```

**Comment by jpas** [comment]
Is there anything deeper in the call stack for this? I'd like to know when `_recv` is being called.

It shouldn't be called unless `self._connected` is set and `self._socket` is `None` if it is not set.

**Comment by ottopasuuna** [comment]
Unfortunately that was all I had from the stack trace, and I couldn't see a way to figure out what exactly causes this (or any of the other open bugs). It only seems to happen when I'm using the ProcessManager's remote api, so trying to start and stop processes on remote machines repeatedly. Otherwise everything seems stable for the most part.

**Comment by jpas** [comment]
I think this bug has something to do with the `__exit__` method of `ProcessManager` ([source](https://github.com/UofSSpaceTeam/robocluster/blob/dev/robocluster/manager/ProcessManager.py#L141-L150)).

Using the event loop directly like that is probably causing this issue. Maybe use use `Futures` and `loop.call_soon_threadsafe` is a solution?
